package com.armutlu.apporganizer.domain.usecase.classify

import com.armutlu.apporganizer.domain.models.AppInfo
import com.armutlu.apporganizer.domain.models.Category
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AppClassifier @Inject constructor() {

    // Üretici bazlı sınıflandırma toggle — AppListViewModel tarafından set edilir
    var manufacturerClassifyEnabled: Boolean = true

    // Üretici prefix → kategori: exactMap'ten sonra, keyword'den önce kontrol edilir
    private val MANUFACTURER_PREFIX_MAP = mapOf(
        // Samsung sistem uygulamaları
        "com.samsung.android.app.galaxyfinder"  to Category.CAT_UTILITIES,
        "com.samsung.android.themestore"        to Category.CAT_UTILITIES,
        "com.samsung.android.personalpage"      to Category.CAT_UTILITIES,
        // Samsung medya/eğlence
        "com.samsung.android.video"             to Category.CAT_ENTERTAINMENT,
        "com.samsung.android.music"             to Category.CAT_ENTERTAINMENT,
        "com.samsung.android.gallery3d"         to Category.CAT_PHOTOGRAPHY,
        // Huawei
        "com.huawei.himovie"                    to Category.CAT_ENTERTAINMENT,
        "com.huawei.music"                      to Category.CAT_ENTERTAINMENT,
        "com.huawei.gallery"                    to Category.CAT_PHOTOGRAPHY,
        // Xiaomi/MIUI
        "com.miui.gallery"                      to Category.CAT_PHOTOGRAPHY,
        "com.miui.videoplayer"                  to Category.CAT_ENTERTAINMENT,
        "com.miui.music"                        to Category.CAT_ENTERTAINMENT,
        // Sony
        "com.sonyericsson.album"                to Category.CAT_PHOTOGRAPHY,
        "com.sonymobile.music"                  to Category.CAT_ENTERTAINMENT,
        // LG
        "com.lge.gallery"                       to Category.CAT_PHOTOGRAPHY,
        "com.lge.music"                         to Category.CAT_ENTERTAINMENT,
    )

    // Paket adına göre kesin kategori eşlemesi — keyword'den önce kontrol edilir
    private val exactMatchMap = mapOf(
        // ── SOCIAL ──────────────────────────────────────────────────────────
        "com.facebook.katana"                        to Category.CAT_SOCIAL,
        "com.facebook.lite"                          to Category.CAT_SOCIAL,
        "com.instagram.android"                      to Category.CAT_SOCIAL,
        "com.twitter.android"                        to Category.CAT_SOCIAL,
        "com.whatsapp"                               to Category.CAT_SOCIAL,
        "com.whatsapp.w4b"                           to Category.CAT_SOCIAL,
        "org.telegram.messenger"                     to Category.CAT_SOCIAL,
        "org.telegram.messenger.web"                 to Category.CAT_SOCIAL,
        "org.thunderdog.challegram"                  to Category.CAT_SOCIAL,
        "com.discord"                                to Category.CAT_SOCIAL,
        "com.snapchat.android"                       to Category.CAT_SOCIAL,
        "com.zhiliaoapp.musically"                   to Category.CAT_SOCIAL,
        "com.ss.android.ugc.trill"                   to Category.CAT_SOCIAL,
        "com.facebook.orca"                          to Category.CAT_SOCIAL,
        "com.linkedin.android"                       to Category.CAT_SOCIAL,
        "com.reddit.frontpage"                       to Category.CAT_SOCIAL,
        "com.pinterest"                              to Category.CAT_SOCIAL,
        "com.tumblr"                                 to Category.CAT_SOCIAL,
        "com.quora.android"                          to Category.CAT_SOCIAL,
        "kik.android"                                to Category.CAT_SOCIAL,
        "com.viber.voip"                             to Category.CAT_SOCIAL,
        "com.skype.raider"                           to Category.CAT_SOCIAL,
        "com.google.android.talk"                    to Category.CAT_SOCIAL,
        "com.bereal.ft"                              to Category.CAT_SOCIAL,
        "app.bsky.social"                            to Category.CAT_SOCIAL,
        "com.instagram.threads"                      to Category.CAT_SOCIAL,
        "com.vkontakte.android"                      to Category.CAT_SOCIAL,
        "jp.naver.line.android"                      to Category.CAT_SOCIAL,
        "com.kakao.talk"                             to Category.CAT_SOCIAL,
        "com.tencent.mm"                             to Category.CAT_SOCIAL,
        "org.thoughtcrime.securesms"                 to Category.CAT_SOCIAL,
        "chat.signal"                                to Category.CAT_SOCIAL,
        "com.wire"                                   to Category.CAT_SOCIAL,
        "com.element.messenger.android"              to Category.CAT_SOCIAL,
        "com.mastodon.android"                       to Category.CAT_SOCIAL,
        "com.twitter.android.lite"                   to Category.CAT_SOCIAL,
        "com.truecaller"                             to Category.CAT_SOCIAL,
        "com.turkcell.bip"                           to Category.CAT_SOCIAL,
        "com.turkcell.bip.lite"                      to Category.CAT_SOCIAL,
        "com.instagram.lite"                         to Category.CAT_SOCIAL,
        "com.facebook.pages.app"                     to Category.CAT_SOCIAL,
        "com.linkedin.android.jobs"                  to Category.CAT_SOCIAL,
        "com.clubhouse"                              to Category.CAT_SOCIAL,
        "com.imo.android.imoim"                      to Category.CAT_SOCIAL,
        "com.zalo"                                   to Category.CAT_SOCIAL,
        "com.nhn.android.band"                       to Category.CAT_SOCIAL,
        "com.mewe.social"                            to Category.CAT_SOCIAL,
        "com.nextdoor"                               to Category.CAT_SOCIAL,
        "com.badoo.mobile"                           to Category.CAT_SOCIAL,
        "com.bumble.app"                             to Category.CAT_SOCIAL,
        "com.tinder"                                 to Category.CAT_SOCIAL,
        "com.grindr.android"                         to Category.CAT_SOCIAL,
        "com.hinge.app"                              to Category.CAT_SOCIAL,
        "com.okcupid.okcupid"                        to Category.CAT_SOCIAL,
        "com.happn.app"                              to Category.CAT_SOCIAL,
        "com.pof.android"                            to Category.CAT_SOCIAL,

        // ── GAMES ────────────────────────────────────────────────────────────
        "com.valvesoftware.android.steam.steamlink"  to Category.CAT_GAMES,
        "com.supercell.clashofclans"                 to Category.CAT_GAMES,
        "com.supercell.clashroyale"                  to Category.CAT_GAMES,
        "com.supercell.brawlstars"                   to Category.CAT_GAMES,
        "com.supercell.hayday"                       to Category.CAT_GAMES,
        "com.king.candycrushsaga"                    to Category.CAT_GAMES,
        "com.king.candycrushsodasaga"                to Category.CAT_GAMES,
        "com.mojang.minecraftpe"                     to Category.CAT_GAMES,
        "com.roblox.client"                          to Category.CAT_GAMES,
        "com.pubg.krmobile"                          to Category.CAT_GAMES,
        "com.tencent.ig"                             to Category.CAT_GAMES,
        "com.garena.game.freefire"                   to Category.CAT_GAMES,
        "com.epicgames.fortnite"                     to Category.CAT_GAMES,
        "com.activision.callofduty.shooter"          to Category.CAT_GAMES,
        "com.miHoYo.GenshinImpact"                   to Category.CAT_GAMES,
        "com.miHoYo.HonkaiStarRail"                  to Category.CAT_GAMES,
        "com.miHoYo.hkrpg"                           to Category.CAT_GAMES,
        "com.plarium.raidlegends"                    to Category.CAT_GAMES,
        "com.ea.game.pvzfree.row"                    to Category.CAT_GAMES,
        "com.ea.games.r3_row"                        to Category.CAT_GAMES,
        "com.ea.game.nfs14_row"                      to Category.CAT_GAMES,
        "com.ea.gp.fifamobile"                       to Category.CAT_GAMES,
        "com.miniclip.eightballpool"                 to Category.CAT_GAMES,
        "com.miniclip.eightball"                     to Category.CAT_GAMES,
        "com.outfit7.mytalkingtom2"                  to Category.CAT_GAMES,
        "com.imangi.templerun2"                      to Category.CAT_GAMES,
        "com.kiloo.subwaysurf"                       to Category.CAT_GAMES,
        "com.halfbrick.fruitninja"                   to Category.CAT_GAMES,
        "com.halfbrick.fruitninjafree"               to Category.CAT_GAMES,
        "com.rovio.angrybirdsreloaded"               to Category.CAT_GAMES,
        "com.nianticlabs.pokemongo"                  to Category.CAT_GAMES,
        "com.zynga.livepoker"                        to Category.CAT_GAMES,
        "com.playrix.gardenscapes"                   to Category.CAT_GAMES,
        "com.playrix.homescapes"                     to Category.CAT_GAMES,
        "com.chess"                                  to Category.CAT_GAMES,
        "com.lichess.mobileapp"                      to Category.CAT_GAMES,
        "com.yodo1.crossyroad"                       to Category.CAT_GAMES,
        "com.scopely.monopolygo"                     to Category.CAT_GAMES,
        "com.scopely.monopoly"                       to Category.CAT_GAMES,
        "com.innersloth.spacemafia"                  to Category.CAT_GAMES,
        "com.mobile.legends"                         to Category.CAT_GAMES,
        "com.dts.freefireth"                         to Category.CAT_GAMES,
        "com.garena.freefiremax"                     to Category.CAT_GAMES,
        "com.levelinfinite.hotta"                    to Category.CAT_GAMES,
        "com.blizzard.diablo.immortal"               to Category.CAT_GAMES,
        "com.codeglue.gg.brawlhalla"                 to Category.CAT_GAMES,
        "com.wordfeud.free"                          to Category.CAT_GAMES,
        "com.gameloft.android.ANMP.GloftA9HM"        to Category.CAT_GAMES,
        "com.outfit7.talkingtomgoldrun"              to Category.CAT_GAMES,
        "com.kabam.marvelbattle"                     to Category.CAT_GAMES,

        // ── ENTERTAINMENT ────────────────────────────────────────────────────
        "com.netflix.mediaclient"                    to Category.CAT_ENTERTAINMENT,
        "com.spotify.music"                          to Category.CAT_ENTERTAINMENT,
        "com.google.android.youtube"                 to Category.CAT_ENTERTAINMENT,
        "com.google.android.youtube.tv"              to Category.CAT_ENTERTAINMENT,
        "com.google.android.apps.youtube.music"      to Category.CAT_ENTERTAINMENT,
        "com.amazon.avod.thirdpartyclient"           to Category.CAT_ENTERTAINMENT,
        "com.disney.disneyplus"                      to Category.CAT_ENTERTAINMENT,
        "tv.twitch.android.app"                      to Category.CAT_ENTERTAINMENT,
        "com.hulu.plus"                              to Category.CAT_ENTERTAINMENT,
        "com.hbo.hbonow"                             to Category.CAT_ENTERTAINMENT,
        "com.peacocktv.peacockandroid"               to Category.CAT_ENTERTAINMENT,
        "com.apple.android.music"                    to Category.CAT_ENTERTAINMENT,
        "com.soundcloud.android"                     to Category.CAT_ENTERTAINMENT,
        "com.deezer.android"                         to Category.CAT_ENTERTAINMENT,
        "com.tidal.android"                          to Category.CAT_ENTERTAINMENT,
        "com.shazam.android"                         to Category.CAT_ENTERTAINMENT,
        "tunein.player"                              to Category.CAT_ENTERTAINMENT,
        "com.pandora.android"                        to Category.CAT_ENTERTAINMENT,
        "org.videolan.vlc"                           to Category.CAT_ENTERTAINMENT,
        "com.mxtech.videoplayer.ad"                  to Category.CAT_ENTERTAINMENT,
        "com.mxtech.videoplayer.pro"                 to Category.CAT_ENTERTAINMENT,
        "com.crunchyroll.crunchyroid"                to Category.CAT_ENTERTAINMENT,
        "com.funimation.funimation"                  to Category.CAT_ENTERTAINMENT,
        "com.imdb.mobile"                            to Category.CAT_ENTERTAINMENT,
        "com.google.android.videos"                  to Category.CAT_ENTERTAINMENT,
        "com.plex.android"                           to Category.CAT_ENTERTAINMENT,
        "com.plexapp.android"                        to Category.CAT_ENTERTAINMENT,
        "io.plex.plex"                               to Category.CAT_ENTERTAINMENT,
        "com.jellyfin.androidtv"                     to Category.CAT_ENTERTAINMENT,
        "com.kodi"                                   to Category.CAT_ENTERTAINMENT,
        "com.audible.application"                    to Category.CAT_ENTERTAINMENT,
        "com.podbean.app"                            to Category.CAT_ENTERTAINMENT,
        "com.pocket.casts"                           to Category.CAT_ENTERTAINMENT,
        "com.blu.tv"                                 to Category.CAT_ENTERTAINMENT,
        "com.exxen.android"                          to Category.CAT_ENTERTAINMENT,
        "com.blutv.android"                          to Category.CAT_ENTERTAINMENT,
        "com.anghami"                                to Category.CAT_ENTERTAINMENT,
        "tv.danmaku.bili"                            to Category.CAT_ENTERTAINMENT,
        "com.yandex.music"                           to Category.CAT_ENTERTAINMENT,
        "com.vk.video"                               to Category.CAT_ENTERTAINMENT,
        "com.d_smart.android"                        to Category.CAT_ENTERTAINMENT,
        "com.digiturk.digiturkplay"                  to Category.CAT_ENTERTAINMENT,
        "com.trt.izle"                               to Category.CAT_ENTERTAINMENT,
        "com.trt.cocuk"                              to Category.CAT_ENTERTAINMENT,
        "com.gain.android"                           to Category.CAT_ENTERTAINMENT,
        "com.puhutv.android"                         to Category.CAT_ENTERTAINMENT,
        "com.tabii.android"                          to Category.CAT_ENTERTAINMENT,
        "com.fizy.android"                           to Category.CAT_ENTERTAINMENT,
        "com.muud.android"                           to Category.CAT_ENTERTAINMENT,
        "com.superpeer.android"                      to Category.CAT_ENTERTAINMENT,

        // ── SHOPPING ─────────────────────────────────────────────────────────
        "com.amazon.mShop.android.shopping"          to Category.CAT_SHOPPING,
        "com.ebay.mobile"                            to Category.CAT_SHOPPING,
        "com.alibaba.aliexpresshd"                   to Category.CAT_SHOPPING,
        "com.alibaba.intl.android.apps.poseidon"     to Category.CAT_SHOPPING,
        "com.trendyol.android"                       to Category.CAT_SHOPPING,
        "com.hepsiburada.android"                    to Category.CAT_SHOPPING,
        "com.n11.android"                            to Category.CAT_SHOPPING,
        "com.sahibinden.android"                     to Category.CAT_SHOPPING,
        "com.letgo.android"                          to Category.CAT_SHOPPING,
        "com.shein.shopping"                         to Category.CAT_SHOPPING,
        "com.wish.android"                           to Category.CAT_SHOPPING,
        "com.shopify.android"                        to Category.CAT_SHOPPING,
        "com.etsy.android"                           to Category.CAT_SHOPPING,
        "com.walmart.android"                        to Category.CAT_SHOPPING,
        "com.target.ui"                              to Category.CAT_SHOPPING,
        "com.vinted.android"                         to Category.CAT_SHOPPING,
        "com.depop"                                  to Category.CAT_SHOPPING,
        "com.poshmark.app"                           to Category.CAT_SHOPPING,
        "com.lazada.android"                         to Category.CAT_SHOPPING,
        "com.shopee.sg"                              to Category.CAT_SHOPPING,
        "com.shopee.ph"                              to Category.CAT_SHOPPING,
        "com.tokopedia.tkpd"                         to Category.CAT_SHOPPING,
        "com.bukalapak.android"                      to Category.CAT_SHOPPING,
        "com.zara.android"                           to Category.CAT_SHOPPING,
        "com.hm.goe"                                 to Category.CAT_SHOPPING,
        "com.asos.app"                               to Category.CAT_SHOPPING,
        "com.zalando.mobile"                         to Category.CAT_SHOPPING,
        "com.farfetch.android"                       to Category.CAT_SHOPPING,
        "com.gittigidiyor.android"                   to Category.CAT_SHOPPING,
        "com.modanisa.android"                       to Category.CAT_SHOPPING,
        "com.lcwaikiki.mobile"                       to Category.CAT_SHOPPING,
        "com.boyner.android"                         to Category.CAT_SHOPPING,
        "com.ciceksepeti.android"                    to Category.CAT_SHOPPING,
        "com.ciceksepeti.mobile"                     to Category.CAT_SHOPPING,
        "com.koton.android"                          to Category.CAT_SHOPPING,
        "com.mavi.android"                           to Category.CAT_SHOPPING,
        "com.defacto.android"                        to Category.CAT_SHOPPING,
        "com.vatanbilgisayar.android"                to Category.CAT_SHOPPING,
        "com.mediamarkt.tr.android"                  to Category.CAT_SHOPPING,
        "com.teknosa.android"                        to Category.CAT_SHOPPING,
        "com.pttavm.android"                         to Category.CAT_SHOPPING,
        "com.dolap.android"                          to Category.CAT_SHOPPING,

        // ── FINANCE ──────────────────────────────────────────────────────────
        "com.paypal.android.p2pmobile"               to Category.CAT_FINANCE,
        "com.venmo"                                  to Category.CAT_FINANCE,
        "com.cashapp"                                to Category.CAT_FINANCE,
        "com.robinhood.android"                      to Category.CAT_FINANCE,
        "com.coinbase.android"                       to Category.CAT_FINANCE,
        "com.binance.dev"                            to Category.CAT_FINANCE,
        "com.kraken.invest.app"                      to Category.CAT_FINANCE,
        "io.metamask"                                to Category.CAT_FINANCE,
        "com.trustwallet.app"                        to Category.CAT_FINANCE,
        "com.revolut.revolut"                        to Category.CAT_FINANCE,
        "com.n26.android"                            to Category.CAT_FINANCE,
        "com.wise.android"                           to Category.CAT_FINANCE,
        "com.monzo.android"                          to Category.CAT_FINANCE,
        "com.starlingbank.android"                   to Category.CAT_FINANCE,
        "com.klarna.shopping"                        to Category.CAT_FINANCE,
        "com.ziraat.android.phone"                   to Category.CAT_FINANCE,
        "com.akbank.android"                         to Category.CAT_FINANCE,
        "com.yapikredibanka.android"                 to Category.CAT_FINANCE,
        "com.garantibbva.android.phone"              to Category.CAT_FINANCE,
        "com.halkbank.android"                       to Category.CAT_FINANCE,
        "com.vakifbank.mobile"                       to Category.CAT_FINANCE,
        "com.isbankasi.android"                      to Category.CAT_FINANCE,
        "tr.com.papara"                              to Category.CAT_FINANCE,
        "com.paribu.android"                         to Category.CAT_FINANCE,
        "com.btcturk.android"                        to Category.CAT_FINANCE,
        "com.denizbank.mobildeniz"                   to Category.CAT_FINANCE,
        "com.garanti.cepsubesi"                      to Category.CAT_FINANCE,
        "com.isbank.isyatirim"                       to Category.CAT_FINANCE,
        "com.sofi.android"                           to Category.CAT_FINANCE,
        "com.chime.feature"                          to Category.CAT_FINANCE,

        // ── HEALTH ───────────────────────────────────────────────────────────
        "com.google.android.apps.fitness"            to Category.CAT_HEALTH,
        "com.fitbit.FitbitMobile"                    to Category.CAT_HEALTH,
        "com.samsung.health"                         to Category.CAT_HEALTH,
        "com.garmin.android.apps.connectmobile"      to Category.CAT_HEALTH,
        "com.strava.android"                         to Category.CAT_HEALTH,
        "com.nike.plusgps"                           to Category.CAT_HEALTH,
        "com.adidas.running"                         to Category.CAT_HEALTH,
        "com.runtastic.android"                      to Category.CAT_HEALTH,
        "com.myfitnesspal.android"                   to Category.CAT_HEALTH,
        "com.headspace.android"                      to Category.CAT_HEALTH,
        "com.calm.android"                           to Category.CAT_HEALTH,
        "com.insight.timer"                          to Category.CAT_HEALTH,
        "com.peloton.android"                        to Category.CAT_HEALTH,
        "com.google.android.apps.wellbeing"          to Category.CAT_HEALTH,
        "com.doktortakvimi.doktortakvimi"            to Category.CAT_HEALTH,
        "com.whoop.android"                          to Category.CAT_HEALTH,
        "com.oura.ring"                              to Category.CAT_HEALTH,
        "com.zepp.com"                               to Category.CAT_HEALTH,
        "com.huawei.health"                          to Category.CAT_HEALTH,
        "com.noom.weightlosscoach"                   to Category.CAT_HEALTH,
        "com.cronometer.android"                     to Category.CAT_HEALTH,
        "com.flo.health"                             to Category.CAT_HEALTH,
        "com.clue.android"                           to Category.CAT_HEALTH,
        "com.daylio.app"                             to Category.CAT_HEALTH,
        "com.sanvello.android"                       to Category.CAT_HEALTH,
        "com.zocdoc.android"                         to Category.CAT_HEALTH,

        // ── EDUCATION ────────────────────────────────────────────────────────
        "com.duolingo"                               to Category.CAT_EDUCATION,
        "com.busuu.android.sp"                       to Category.CAT_EDUCATION,
        "com.babbel.mobile.android.default"          to Category.CAT_EDUCATION,
        "com.memrise.app"                            to Category.CAT_EDUCATION,
        "com.udemy.android"                          to Category.CAT_EDUCATION,
        "com.coursera.android"                       to Category.CAT_EDUCATION,
        "com.skillshare.skillshare"                  to Category.CAT_EDUCATION,
        "com.edx.mobile"                             to Category.CAT_EDUCATION,
        "org.khanacademy.android"                    to Category.CAT_EDUCATION,
        "com.brilliant.android"                      to Category.CAT_EDUCATION,
        "com.codecademy.android"                     to Category.CAT_EDUCATION,
        "com.sololearn"                              to Category.CAT_EDUCATION,
        "com.mimo.android"                           to Category.CAT_EDUCATION,
        "com.photomath.android"                      to Category.CAT_EDUCATION,
        "com.photomath.app"                          to Category.CAT_EDUCATION,
        "com.wolfram.wolframalpha"                   to Category.CAT_EDUCATION,
        "com.anki.android"                           to Category.CAT_EDUCATION,
        "com.quizlet.quizletandroid"                 to Category.CAT_EDUCATION,
        "com.quizlet.flashcards"                     to Category.CAT_EDUCATION,
        "com.scribd.app.reader0"                     to Category.CAT_EDUCATION,
        "com.blinkist.android"                       to Category.CAT_EDUCATION,
        "com.ted.android"                            to Category.CAT_EDUCATION,
        "com.masterclass.android"                    to Category.CAT_EDUCATION,
        "com.eba.android"                            to Category.CAT_EDUCATION,

        // ── TRAVEL ───────────────────────────────────────────────────────────
        "com.ubercab"                                to Category.CAT_TRAVEL,
        "com.lyft.android"                           to Category.CAT_TRAVEL,
        "com.lyft"                                   to Category.CAT_TRAVEL,
        "com.booking"                                to Category.CAT_TRAVEL,
        "com.airbnb.android"                         to Category.CAT_TRAVEL,
        "com.flightradar24.free"                     to Category.CAT_TRAVEL,
        "com.flightradar24.flightradar24"             to Category.CAT_TRAVEL,
        "com.tripadvisor.tripadvisor"                to Category.CAT_TRAVEL,
        "com.google.android.apps.maps"               to Category.CAT_TRAVEL,
        "com.yandex.maps"                            to Category.CAT_TRAVEL,
        "com.waze"                                   to Category.CAT_TRAVEL,
        "com.expedia.android"                        to Category.CAT_TRAVEL,
        "com.kayak.android"                          to Category.CAT_TRAVEL,
        "net.skyscanner.android.main"                to Category.CAT_TRAVEL,
        "com.here.app.maps"                          to Category.CAT_TRAVEL,
        "com.sygic.aura"                             to Category.CAT_TRAVEL,
        "com.transit.android"                        to Category.CAT_TRAVEL,
        "com.citymapper.android"                     to Category.CAT_TRAVEL,
        "com.moovit.moovitapp"                       to Category.CAT_TRAVEL,
        "com.bolt.client"                            to Category.CAT_TRAVEL,
        "com.indriver.app"                           to Category.CAT_TRAVEL,
        "com.turkish.airlines"                       to Category.CAT_TRAVEL,
        "com.obilet.android"                         to Category.CAT_TRAVEL,
        "com.enuygun.android"                        to Category.CAT_TRAVEL,
        "com.belbim.istanbulkart"                    to Category.CAT_TRAVEL,
        "com.bitaksi.android"                        to Category.CAT_TRAVEL,
        "com.pegasusapp.android"                     to Category.CAT_TRAVEL,
        "com.trivago"                                to Category.CAT_TRAVEL,
        "com.marti.mopet"                            to Category.CAT_TRAVEL,
        "com.martiscooter.android"                   to Category.CAT_TRAVEL,
        "com.hepsiburada.seyahat"                    to Category.CAT_TRAVEL,
        "com.kentkart.android"                       to Category.CAT_TRAVEL,
        "com.tcdd.bilet"                             to Category.CAT_TRAVEL,
        "com.milpark.ido"                            to Category.CAT_TRAVEL,
        "com.iett.android"                           to Category.CAT_TRAVEL,
        "com.ido.android"                            to Category.CAT_TRAVEL,

        // ── PRODUCTIVITY ─────────────────────────────────────────────────────
        "com.openai.chatgpt"                         to Category.CAT_PRODUCTIVITY,
        "com.openai.android"                         to Category.CAT_PRODUCTIVITY,
        "com.deepseek.app"                           to Category.CAT_PRODUCTIVITY,
        "ai.deepseek.app"                            to Category.CAT_PRODUCTIVITY,
        "com.deepseek.chat"                          to Category.CAT_PRODUCTIVITY,
        "com.anthropic.claude"                       to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.bard"               to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.gemini"             to Category.CAT_PRODUCTIVITY,
        "com.microsoft.copilot"                      to Category.CAT_PRODUCTIVITY,
        "com.perplexity.app"                         to Category.CAT_PRODUCTIVITY,
        "ai.perplexity.app.android"                  to Category.CAT_PRODUCTIVITY,
        "io.character.ai"                            to Category.CAT_PRODUCTIVITY,
        "com.google.android.gm"                      to Category.CAT_PRODUCTIVITY,
        "com.google.android.calendar"                to Category.CAT_PRODUCTIVITY,
        "com.google.android.keep"                    to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.docs"               to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.sheets"             to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.presentations"      to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.tasks"              to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.drive"              to Category.CAT_PRODUCTIVITY,
        "com.microsoft.office.word"                  to Category.CAT_PRODUCTIVITY,
        "com.microsoft.office.excel"                 to Category.CAT_PRODUCTIVITY,
        "com.microsoft.office.powerpoint"            to Category.CAT_PRODUCTIVITY,
        "com.microsoft.office.outlook"               to Category.CAT_PRODUCTIVITY,
        "com.microsoft.teams"                        to Category.CAT_PRODUCTIVITY,
        "com.microsoft.onenote"                      to Category.CAT_PRODUCTIVITY,
        "com.microsoft.skydrive"                     to Category.CAT_PRODUCTIVITY,
        "us.zoom.videomeetings"                      to Category.CAT_PRODUCTIVITY,
        "com.slack"                                  to Category.CAT_PRODUCTIVITY,
        "com.notion.id"                              to Category.CAT_PRODUCTIVITY,
        "com.evernote"                               to Category.CAT_PRODUCTIVITY,
        "com.todoist.android.Todoist"                to Category.CAT_PRODUCTIVITY,
        "com.asana.android"                          to Category.CAT_PRODUCTIVITY,
        "com.trello"                                 to Category.CAT_PRODUCTIVITY,
        "com.atlassian.android.jira.core"            to Category.CAT_PRODUCTIVITY,
        "com.monday.android"                         to Category.CAT_PRODUCTIVITY,
        "io.clickup.mobile.android"                  to Category.CAT_PRODUCTIVITY,
        "md.obsidian"                                to Category.CAT_PRODUCTIVITY,
        "com.agilebits.onepassword"                  to Category.CAT_PRODUCTIVITY,
        "com.lastpass.lpandroid"                     to Category.CAT_PRODUCTIVITY,
        "com.bitwarden.mobile"                       to Category.CAT_PRODUCTIVITY,
        "com.dropbox.android"                        to Category.CAT_PRODUCTIVITY,
        "com.adobe.acrobat.reader"                   to Category.CAT_PRODUCTIVITY,
        "com.grammarly.android"                      to Category.CAT_PRODUCTIVITY,
        "com.figma.android"                          to Category.CAT_PRODUCTIVITY,
        "com.github.android"                         to Category.CAT_PRODUCTIVITY,
        "com.protonmail.protonmail"                  to Category.CAT_PRODUCTIVITY,
        "com.linear.app"                             to Category.CAT_PRODUCTIVITY,
        "com.craft.docs"                             to Category.CAT_PRODUCTIVITY,
        "com.calendly.android"                       to Category.CAT_PRODUCTIVITY,

        // ── NEWS ─────────────────────────────────────────────────────────────
        "com.google.android.apps.news"               to Category.CAT_NEWS,
        "com.flipboard.app"                          to Category.CAT_NEWS,
        "com.feedly.android"                         to Category.CAT_NEWS,
        "com.medium.android"                         to Category.CAT_NEWS,
        "com.bbc.news"                               to Category.CAT_NEWS,
        "com.cnn.mobile.android.phone"               to Category.CAT_NEWS,
        "com.nytimes.android"                        to Category.CAT_NEWS,
        "com.theguardian.android"                    to Category.CAT_NEWS,
        "com.reuters.news"                           to Category.CAT_NEWS,
        "com.bloomberg.android.bloomberg"            to Category.CAT_NEWS,
        "com.wsj.android"                            to Category.CAT_NEWS,
        "com.aljazeera.english"                      to Category.CAT_NEWS,
        "com.ntv.ntvandroid"                         to Category.CAT_NEWS,
        "com.sabah.android"                          to Category.CAT_NEWS,
        "com.haberturk.android"                      to Category.CAT_NEWS,
        "com.hurriyet.android"                       to Category.CAT_NEWS,
        "com.milliyet.android"                       to Category.CAT_NEWS,
        "com.sozcu.android"                          to Category.CAT_NEWS,
        "com.techcrunch.android"                     to Category.CAT_NEWS,
        "com.theverge.android"                       to Category.CAT_NEWS,
        "com.wired.android"                          to Category.CAT_NEWS,
        "com.businessinsider.android"                to Category.CAT_NEWS,

        // ── UTILITIES ────────────────────────────────────────────────────────
        "com.android.chrome"                         to Category.CAT_UTILITIES,
        "org.mozilla.firefox"                        to Category.CAT_UTILITIES,
        "com.opera.browser"                          to Category.CAT_UTILITIES,
        "com.brave.browser"                          to Category.CAT_UTILITIES,
        "com.duckduckgo.mobile.android"              to Category.CAT_UTILITIES,
        "com.microsoft.emmx"                         to Category.CAT_UTILITIES,
        "com.vivaldi.browser"                        to Category.CAT_UTILITIES,
        "org.torproject.torbrowser"                  to Category.CAT_UTILITIES,
        "com.expressvpn.vpn"                         to Category.CAT_UTILITIES,
        "com.nordvpn.android"                        to Category.CAT_UTILITIES,
        "com.surfshark.vpnclient.android"            to Category.CAT_UTILITIES,
        "com.protonvpn.android"                      to Category.CAT_UTILITIES,
        "com.mullvad.vpn"                            to Category.CAT_UTILITIES,
        "com.proton.android"                         to Category.CAT_UTILITIES,
        "com.google.android.inputmethod.latin"       to Category.CAT_UTILITIES,
        "com.touchtype.swiftkey"                     to Category.CAT_UTILITIES,
        "com.google.android.apps.authenticator2"     to Category.CAT_UTILITIES,
        "com.authy.authy"                            to Category.CAT_UTILITIES,
        "com.microsoft.authenticator"                to Category.CAT_UTILITIES,
        "com.google.android.apps.translate"          to Category.CAT_UTILITIES,
        "com.deepl.android"                          to Category.CAT_UTILITIES,
        "com.microsoft.translator"                   to Category.CAT_UTILITIES,
        "com.yandex.translate"                       to Category.CAT_UTILITIES,
        "com.google.android.calculator"              to Category.CAT_UTILITIES,
        "com.speedtest.by.ookla"                     to Category.CAT_UTILITIES,
        "com.avast.android.mobilesecurity"           to Category.CAT_UTILITIES,
        "com.bitdefender.security"                   to Category.CAT_UTILITIES,
        "com.kaspersky.kes.android"                  to Category.CAT_UTILITIES,
        "com.actionlauncher.playstore"               to Category.CAT_UTILITIES,
        "com.teslacoilsw.launcher"                   to Category.CAT_UTILITIES,
        "com.windscribe.vpn"                         to Category.CAT_UTILITIES,

        // ── FOOD ─────────────────────────────────────────────────────────────
        "com.doordash.ddshopper"                     to Category.CAT_FOOD,
        "com.ubereats"                               to Category.CAT_FOOD,
        "com.grubhub.android"                        to Category.CAT_FOOD,
        "com.global.deliveroo.orderapp"              to Category.CAT_FOOD,
        "com.instacart.groceries"                    to Category.CAT_FOOD,
        "com.starbucks.mobilecard"                   to Category.CAT_FOOD,
        "com.mcdonalds.app"                          to Category.CAT_FOOD,
        "com.burgerking.android"                     to Category.CAT_FOOD,
        "com.dominos.android"                        to Category.CAT_FOOD,
        "com.pizzahut.android"                       to Category.CAT_FOOD,
        "com.yelp.android"                           to Category.CAT_FOOD,
        "com.zomato.android"                         to Category.CAT_FOOD,
        "com.yummly.android"                         to Category.CAT_FOOD,
        "com.allrecipes.android"                     to Category.CAT_FOOD,
        "com.yemeksepeti.android"                    to Category.CAT_FOOD,
        "com.trendyolexpress.android"                to Category.CAT_FOOD,
        "com.migros.sanal.market"                    to Category.CAT_FOOD,
        "com.getir.android"                          to Category.CAT_FOOD,
        "com.getirwater.android"                     to Category.CAT_FOOD,
        "com.a101.android"                           to Category.CAT_FOOD,
        "com.bim.android"                            to Category.CAT_FOOD,
        "com.carrefoursa.android"                    to Category.CAT_FOOD,
        "com.arcelik.android"                        to Category.CAT_FOOD,
        "com.swiggy.android"                         to Category.CAT_FOOD,
        "com.rappi.android"                          to Category.CAT_FOOD,
        "com.talabat"                                to Category.CAT_FOOD,
        "com.foodpanda.android"                      to Category.CAT_FOOD,
        "com.kfc.android"                            to Category.CAT_FOOD,
        "com.subway.mobile"                          to Category.CAT_FOOD,

        // ── PHOTOGRAPHY ──────────────────────────────────────────────────────
        "com.samsung.android.gallery3d"              to Category.CAT_PHOTOGRAPHY,
        "com.adobe.lightroom"                        to Category.CAT_PHOTOGRAPHY,
        "com.adobe.photoshop"                        to Category.CAT_PHOTOGRAPHY,
        "com.canva.android"                          to Category.CAT_PHOTOGRAPHY,
        "com.picsart.studio"                         to Category.CAT_PHOTOGRAPHY,
        "com.vsco.cam"                               to Category.CAT_PHOTOGRAPHY,
        "com.snapseed"                               to Category.CAT_PHOTOGRAPHY,
        "com.inshot.android"                         to Category.CAT_PHOTOGRAPHY,
        "com.capcut.video.editor"                    to Category.CAT_PHOTOGRAPHY,
        "com.youcam.beauty"                          to Category.CAT_PHOTOGRAPHY,
        "com.faceapp"                                to Category.CAT_PHOTOGRAPHY,
        "com.polarr.photo.editor"                    to Category.CAT_PHOTOGRAPHY,
        "com.fotor.android"                          to Category.CAT_PHOTOGRAPHY,
        "com.pixlr.android"                          to Category.CAT_PHOTOGRAPHY,
        "com.picmonkey.android"                      to Category.CAT_PHOTOGRAPHY,
        "com.google.android.GoogleCamera"            to Category.CAT_PHOTOGRAPHY,
        "net.sourceforge.opencamera"                 to Category.CAT_PHOTOGRAPHY,
        "com.lightricks.facetune"                    to Category.CAT_PHOTOGRAPHY,
        "com.lightricks.facetune2"                   to Category.CAT_PHOTOGRAPHY,
        "com.ulike.android"                          to Category.CAT_PHOTOGRAPHY,
        "com.retrica.android"                        to Category.CAT_PHOTOGRAPHY,
        "com.prisma.app"                             to Category.CAT_PHOTOGRAPHY,
        "com.prequel.app.android"                    to Category.CAT_PHOTOGRAPHY,
        "com.kwai.video"                             to Category.CAT_PHOTOGRAPHY,
        "com.triller.android"                        to Category.CAT_PHOTOGRAPHY,
        "com.likee.video"                            to Category.CAT_PHOTOGRAPHY,
        "com.cymera.android"                         to Category.CAT_PHOTOGRAPHY,
        "com.efectum.android"                        to Category.CAT_PHOTOGRAPHY,
        "com.vllo.android"                           to Category.CAT_PHOTOGRAPHY,
        "com.adobe.scan.android"                     to Category.CAT_PHOTOGRAPHY,
        "com.microsoft.office.lens"                  to Category.CAT_PHOTOGRAPHY,
        "com.sweet.selfie.beauty.camera"             to Category.CAT_PHOTOGRAPHY,
        "com.beautycam.android"                      to Category.CAT_PHOTOGRAPHY,
        "com.ufoto.android"                          to Category.CAT_PHOTOGRAPHY,

        // -- GAMES -- ek -------------------------------------------------------
        "com.bandainamcoent.dblegends_ww"            to Category.CAT_GAMES,
        "com.lilithgame.roc.gp"                      to Category.CAT_GAMES,
        "com.habby.archero"                          to Category.CAT_GAMES,
        "com.fingersoft.hillclimb"                   to Category.CAT_GAMES,
        "com.fingersoft.hillclimb2"                  to Category.CAT_GAMES,
        "com.noodlecake.altosodyssey"                to Category.CAT_GAMES,
        "com.noodlecake.altosadventure"              to Category.CAT_GAMES,
        "com.playrix.township"                       to Category.CAT_GAMES,
        "io.voodoo.helix"                            to Category.CAT_GAMES,
        "io.voodoo.paper"                            to Category.CAT_GAMES,
        "io.voodoo.paperio2"                         to Category.CAT_GAMES,
        "io.voodoo.crowd"                            to Category.CAT_GAMES,
        "io.voodoo.stackball3d"                      to Category.CAT_GAMES,
        "com.goodgamestudios.empirefourkingdoms"     to Category.CAT_GAMES,
        "com.goodgamestudios.bigfarmmp"              to Category.CAT_GAMES,
        "com.gameloft.android.ANMP.GloftA8HM"       to Category.CAT_GAMES,
        "com.gameloft.android.ANMP.GloftN3HM"       to Category.CAT_GAMES,
        "com.gameloft.android.ANMP.GloftGRHM"       to Category.CAT_GAMES,
        "com.netmarble.mff"                          to Category.CAT_GAMES,
        "com.miHoYo.Honkai3rd"                      to Category.CAT_GAMES,
        "com.cognosphere.zenlesszone"                to Category.CAT_GAMES,
        "com.miHoYo.zenlesszone"                    to Category.CAT_GAMES,
        "com.kuro.pgr.global"                        to Category.CAT_GAMES,
        "com.imangi.templerun"                       to Category.CAT_GAMES,
        "com.outfit7.mytalkingtom"                   to Category.CAT_GAMES,
        "com.outfit7.talkingtomfriendsapp"           to Category.CAT_GAMES,
        "com.halfbrick.jetpackjoyride"               to Category.CAT_GAMES,
        "com.halfbrick.monsterdash"                  to Category.CAT_GAMES,
        "com.konami.pesam"                           to Category.CAT_GAMES,
        "com.konami.efoot"                           to Category.CAT_GAMES,
        "com.vng.pubgmobile"                         to Category.CAT_GAMES,
        "com.levelinfinite.bgmi"                     to Category.CAT_GAMES,
        "com.tencent.tmgp.pubgmhd"                  to Category.CAT_GAMES,
        "com.riotgames.league.wildrift"              to Category.CAT_GAMES,
        "com.zynga.farmville3"                       to Category.CAT_GAMES,
        "com.zynga.words"                            to Category.CAT_GAMES,
        "com.zynga.slotsstar"                        to Category.CAT_GAMES,
        "com.scopely.yahtzee"                        to Category.CAT_GAMES,
        "com.ea.game.simsmobileglobal"               to Category.CAT_GAMES,
        "com.ea.game.simsFreeplay"                   to Category.CAT_GAMES,
        "com.ea.gp.swgoh"                            to Category.CAT_GAMES,
        "com.miniclip.footballstrike"                to Category.CAT_GAMES,
        "com.miniclip.soccer"                        to Category.CAT_GAMES,
        "com.miniclip.golf"                          to Category.CAT_GAMES,
        "com.playdemic.golf"                         to Category.CAT_GAMES,
        "com.frogmind.badland"                       to Category.CAT_GAMES,
        "com.frogmind.badland2"                      to Category.CAT_GAMES,
        "com.topwar.android"                         to Category.CAT_GAMES,
        "com.wb.goog.mk.phone"                       to Category.CAT_GAMES,
        "com.wb.goog.hpma"                           to Category.CAT_GAMES,
        "com.wb.goog.looneytunes"                    to Category.CAT_GAMES,
        "com.nianticlabs.pikmin"                     to Category.CAT_GAMES,
        "com.nianticlabs.ingress"                    to Category.CAT_GAMES,
        "com.rockstargames.sandreas"                 to Category.CAT_GAMES,
        "com.rockstargames.gtaiii"                   to Category.CAT_GAMES,
        "com.rockstargames.bully"                    to Category.CAT_GAMES,
        "com.rockstargames.maxpayne"                 to Category.CAT_GAMES,
        "com.madfingergames.deadtrigger2"            to Category.CAT_GAMES,
        "com.madfingergames.shadowgunwarlords"       to Category.CAT_GAMES,
        "com.madfingergames.unkilled"                to Category.CAT_GAMES,
        "com.pixonic.wwr"                            to Category.CAT_GAMES,
        "com.pixel.gun3d"                            to Category.CAT_GAMES,
        "net.blockman.games"                         to Category.CAT_GAMES,
        "com.hasbro.monopoly"                        to Category.CAT_GAMES,
        "com.pixelunited.beachbuggy2"                to Category.CAT_GAMES,
        "com.squareenix.android.ff1"                 to Category.CAT_GAMES,
        "com.squareenix.android.ff6"                 to Category.CAT_GAMES,
        "net.kairosoft.android.gameDevStoryEn"       to Category.CAT_GAMES,
        "com.netease.g62na"                          to Category.CAT_GAMES,
        "com.cygames.priconneglobal"                 to Category.CAT_GAMES,
        "com.klab.bleachhm"                          to Category.CAT_GAMES,
        "com.ea.game.starwarsheroes"                 to Category.CAT_GAMES,
        "com.devolver.hotline"                       to Category.CAT_GAMES,
        "com.netmarble.mherosgb"                     to Category.CAT_GAMES,
        "com.kabam.marvelContestofchampions"         to Category.CAT_GAMES,
        "com.ubisoft.rabbids.bigplanets"             to Category.CAT_GAMES,
        "com.habby.penguin"                          to Category.CAT_GAMES,
        "com.habby.snipermaster"                     to Category.CAT_GAMES,
        "com.imangi.templerun2oz"                    to Category.CAT_GAMES,
        "com.ea.game.bfnmobile"                      to Category.CAT_GAMES,

        // -- SOCIAL -- ek -------------------------------------------------------
        "com.meetup.android"                         to Category.CAT_SOCIAL,
        "com.ablo.android"                           to Category.CAT_SOCIAL,
        "com.tapatalk.android"                       to Category.CAT_SOCIAL,
        "com.mix.android"                            to Category.CAT_SOCIAL,
        "com.yikyak.android"                         to Category.CAT_SOCIAL,
        "com.taringa.android"                        to Category.CAT_SOCIAL,
        "com.medium.android"                         to Category.CAT_SOCIAL,
        "com.getdots.android"                        to Category.CAT_SOCIAL,
        "com.locket.widget"                          to Category.CAT_SOCIAL,

        // -- ENTERTAINMENT -- ek -----------------------------------------------
        "com.hbo.hbomax"                             to Category.CAT_ENTERTAINMENT,
        "com.paramountplus.android"                  to Category.CAT_ENTERTAINMENT,
        "com.mubi.android"                           to Category.CAT_ENTERTAINMENT,
        "com.philo.android"                          to Category.CAT_ENTERTAINMENT,
        "com.slingtv.android"                        to Category.CAT_ENTERTAINMENT,
        "com.google.android.videos"                  to Category.CAT_ENTERTAINMENT,
        "com.apple.android.music"                    to Category.CAT_ENTERTAINMENT,
        "com.bbc.sounds"                             to Category.CAT_ENTERTAINMENT,
        "com.iheartradio.android"                    to Category.CAT_ENTERTAINMENT,
        "com.mixcloud.android"                       to Category.CAT_ENTERTAINMENT,
        "com.jio.media.ondemand"                     to Category.CAT_ENTERTAINMENT,
        "com.hotstar.android"                        to Category.CAT_ENTERTAINMENT,
        "com.zee5.android"                           to Category.CAT_ENTERTAINMENT,
        "com.sonyliv.android"                        to Category.CAT_ENTERTAINMENT,
        "com.vuclip.android"                         to Category.CAT_ENTERTAINMENT,
        "com.mxplayer.android"                       to Category.CAT_ENTERTAINMENT,
        "com.bbc.iplayer.android"                    to Category.CAT_ENTERTAINMENT,
        "com.channel4.android"                       to Category.CAT_ENTERTAINMENT,
        "tv.abema.android"                           to Category.CAT_ENTERTAINMENT,
        "com.joox.android"                           to Category.CAT_ENTERTAINMENT,
        "com.resso.android"                          to Category.CAT_ENTERTAINMENT,
        "com.melon.android"                          to Category.CAT_ENTERTAINMENT,

        // -- PRODUCTIVITY -- ek ------------------------------------------------
        "com.readdle.spark"                          to Category.CAT_PRODUCTIVITY,
        "com.superhuman.email"                       to Category.CAT_PRODUCTIVITY,
        "com.fastmail.android"                       to Category.CAT_PRODUCTIVITY,
        "com.tutanota.tutanota"                      to Category.CAT_PRODUCTIVITY,
        "com.zoho.mail.android"                      to Category.CAT_PRODUCTIVITY,
        "com.zoho.notebook"                          to Category.CAT_PRODUCTIVITY,
        "com.basecamp.android"                       to Category.CAT_PRODUCTIVITY,
        "com.logmein.gotomeeting"                    to Category.CAT_PRODUCTIVITY,
        "com.cisco.webex.android"                    to Category.CAT_PRODUCTIVITY,
        "com.microsoft.launcher"                     to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.meet"               to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.classroom"          to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.photos"             to Category.CAT_PRODUCTIVITY,
        "com.google.android.apps.nbu.files"          to Category.CAT_PRODUCTIVITY,
        "com.affinity.photo"                         to Category.CAT_PRODUCTIVITY,
        "com.linear.app"                             to Category.CAT_PRODUCTIVITY,
        "com.superhuman.android"                     to Category.CAT_PRODUCTIVITY,
        "com.anydo.android"                          to Category.CAT_PRODUCTIVITY,
        "com.ticktick.task"                          to Category.CAT_PRODUCTIVITY,
        "com.habitica.android"                       to Category.CAT_PRODUCTIVITY,
        "com.bezel.android"                          to Category.CAT_PRODUCTIVITY,

        // -- FINANCE -- ek -------------------------------------------------------
        "com.etoro.android"                          to Category.CAT_FINANCE,
        "com.tradingview.android"                    to Category.CAT_FINANCE,
        "com.webull.android"                         to Category.CAT_FINANCE,
        "com.investing.android"                      to Category.CAT_FINANCE,
        "com.stash.invest"                           to Category.CAT_FINANCE,
        "com.acorns.android"                         to Category.CAT_FINANCE,
        "com.betterment.android"                     to Category.CAT_FINANCE,
        "com.wealthfront.android"                    to Category.CAT_FINANCE,
        "com.sofi.android"                           to Category.CAT_FINANCE,
        "com.ally.android"                           to Category.CAT_FINANCE,
        "com.discover.android"                       to Category.CAT_FINANCE,
        "com.barclays.android"                       to Category.CAT_FINANCE,
        "com.hsbc.android"                           to Category.CAT_FINANCE,
        "com.santander.android"                      to Category.CAT_FINANCE,
        "com.ing.android"                            to Category.CAT_FINANCE,
        "com.square.android"                         to Category.CAT_FINANCE,
        "com.odeabank.mobile"                        to Category.CAT_FINANCE,
        "com.fibabanka.android"                      to Category.CAT_FINANCE,
        "com.kuveytturk.android"                     to Category.CAT_FINANCE,
        "com.albaraka.android"                       to Category.CAT_FINANCE,
        "com.qnbfinansbank.android"                  to Category.CAT_FINANCE,
        "com.teb.android"                            to Category.CAT_FINANCE,
        "com.sekerbank.android"                      to Category.CAT_FINANCE,
        "com.tosla.android"                          to Category.CAT_FINANCE,
        "com.iyzico.android"                         to Category.CAT_FINANCE,
        "com.fastpay.android"                        to Category.CAT_FINANCE,
        "com.param.android"                          to Category.CAT_FINANCE,
        "com.goldenpay.android"                      to Category.CAT_FINANCE,
        "com.kraken.invest.app"                      to Category.CAT_FINANCE,
        "com.okex.android"                           to Category.CAT_FINANCE,
        "com.bybit.android"                          to Category.CAT_FINANCE,
        "com.gate.io"                                to Category.CAT_FINANCE,
        "com.kucoin.android"                         to Category.CAT_FINANCE,

        // -- HEALTH -- ek -------------------------------------------------------
        "com.webmd.android"                          to Category.CAT_HEALTH,
        "com.ada.android"                            to Category.CAT_HEALTH,
        "com.runkeeper.android"                      to Category.CAT_HEALTH,
        "com.mapmyrun.android"                       to Category.CAT_HEALTH,
        "com.mapmyfitness.android"                   to Category.CAT_HEALTH,
        "com.sworkit.android"                        to Category.CAT_HEALTH,
        "com.seven.app"                              to Category.CAT_HEALTH,
        "com.runtastic.adidas.android"               to Category.CAT_HEALTH,
        "com.adidas.running.universal"               to Category.CAT_HEALTH,
        "com.polar.polarbeat"                        to Category.CAT_HEALTH,
        "com.wahoo.fitness"                          to Category.CAT_HEALTH,
        "com.withings.android"                       to Category.CAT_HEALTH,
        "com.coros.android"                          to Category.CAT_HEALTH,
        "com.medisafe.android.client"                to Category.CAT_HEALTH,
        "com.loseit.android"                         to Category.CAT_HEALTH,
        "com.mynetdiary.android.calorie"             to Category.CAT_HEALTH,
        "com.glow.glow"                              to Category.CAT_HEALTH,
        "com.ovia.fertility"                         to Category.CAT_HEALTH,
        "com.acibadem.android"                       to Category.CAT_HEALTH,
        "com.medicalpark.android"                    to Category.CAT_HEALTH,

        // -- EDUCATION -- ek ----------------------------------------------------
        "com.rosettastone.mobile.learner"            to Category.CAT_EDUCATION,
        "com.lingodeer.android"                      to Category.CAT_EDUCATION,
        "com.cambridgedictionary.android"            to Category.CAT_EDUCATION,
        "com.merriam.webster.android"                to Category.CAT_EDUCATION,
        "com.oxforddictionary.android"               to Category.CAT_EDUCATION,
        "com.lumos.lumosity"                         to Category.CAT_EDUCATION,
        "com.elevate.brain"                          to Category.CAT_EDUCATION,
        "com.peak.android"                           to Category.CAT_EDUCATION,
        "com.brainscape.android"                     to Category.CAT_EDUCATION,
        "com.mathway.android"                        to Category.CAT_EDUCATION,
        "com.symbolab.android"                       to Category.CAT_EDUCATION,
        "com.desmos.calculator"                      to Category.CAT_EDUCATION,
        "com.geogebra.android"                       to Category.CAT_EDUCATION,
        "com.instructure.candroid"                   to Category.CAT_EDUCATION,
        "com.blackboard.bb.mobile"                   to Category.CAT_EDUCATION,
        "com.classdojo.android"                      to Category.CAT_EDUCATION,
        "com.moodle.moodlemobile"                    to Category.CAT_EDUCATION,
        "com.byju.app"                               to Category.CAT_EDUCATION,
        "com.chegg.android"                          to Category.CAT_EDUCATION,
        "com.pimsleur.learn"                         to Category.CAT_EDUCATION,
        "com.morpaegitim.android"                    to Category.CAT_EDUCATION,
        "com.dersdergi.android"                      to Category.CAT_EDUCATION,

        // -- TRAVEL -- ek -------------------------------------------------------
        "com.airfrance.android"                      to Category.CAT_TRAVEL,
        "com.klm.android"                            to Category.CAT_TRAVEL,
        "com.united.android"                         to Category.CAT_TRAVEL,
        "com.aa.android"                             to Category.CAT_TRAVEL,
        "com.ryanair.cheapflights"                   to Category.CAT_TRAVEL,
        "com.easyjet.android"                        to Category.CAT_TRAVEL,
        "com.hotels.android"                         to Category.CAT_TRAVEL,
        "com.agoda.mobile.consumer"                  to Category.CAT_TRAVEL,
        "com.hostelworld.android"                    to Category.CAT_TRAVEL,
        "com.makemytrip.android"                     to Category.CAT_TRAVEL,
        "com.trainline.android"                      to Category.CAT_TRAVEL,
        "com.rome2rio.android"                       to Category.CAT_TRAVEL,
        "com.cabify.android"                         to Category.CAT_TRAVEL,
        "com.turo.android"                           to Category.CAT_TRAVEL,
        "com.anadolujet.android"                     to Category.CAT_TRAVEL,
        "com.sunexpress.android"                     to Category.CAT_TRAVEL,
        "com.hertz.android"                          to Category.CAT_TRAVEL,
        "com.enterprise.android"                     to Category.CAT_TRAVEL,
        "com.aircanada.android"                      to Category.CAT_TRAVEL,
        "com.emirates.android"                       to Category.CAT_TRAVEL,

        // -- UTILITIES -- ek ----------------------------------------------------
        "com.estrongs.android.pop"                   to Category.CAT_UTILITIES,
        "com.ghisler.android"                        to Category.CAT_UTILITIES,
        "com.mi.android.globalFileexplorer"          to Category.CAT_UTILITIES,
        "com.shareit.alliance"                       to Category.CAT_UTILITIES,
        "com.teamviewer.teamviewer"                  to Category.CAT_UTILITIES,
        "com.anydesk.anydeskandroid"                 to Category.CAT_UTILITIES,
        "com.opera.mini.native"                      to Category.CAT_UTILITIES,
        "com.UCMobile.intl"                          to Category.CAT_UTILITIES,
        "com.adguard.android"                        to Category.CAT_UTILITIES,
        "com.avira.android"                          to Category.CAT_UTILITIES,
        "com.symantec.mobilesecurity"                to Category.CAT_UTILITIES,
        "com.lookout.android"                        to Category.CAT_UTILITIES,
        "com.mcafee.vsm"                             to Category.CAT_UTILITIES,
        "com.iobit.mobilecare"                       to Category.CAT_UTILITIES,
        "org.fdroid.fdroid"                          to Category.CAT_UTILITIES,
        "com.nhn.android.nmap"                       to Category.CAT_UTILITIES,
        "com.google.android.apps.wallpaper"          to Category.CAT_UTILITIES,
        "com.google.android.gms"                     to Category.CAT_UTILITIES,
        "com.android.vending"                        to Category.CAT_UTILITIES,
        "com.xiaomi.smarthome"                       to Category.CAT_UTILITIES,
        "com.samsung.android.smartthings"            to Category.CAT_UTILITIES,
        "com.philips.lighting.hue"                   to Category.CAT_UTILITIES,
        "com.google.android.apps.barcode"            to Category.CAT_UTILITIES,
        "com.qr.barcode.scanner"                     to Category.CAT_UTILITIES,

        // -- FOOD -- ek ---------------------------------------------------------
        "com.postmates.android"                      to Category.CAT_FOOD,
        "com.seamless.android"                       to Category.CAT_FOOD,
        "com.just.eat.android"                       to Category.CAT_FOOD,
        "com.hungerstation.android"                  to Category.CAT_FOOD,
        "com.careem.android"                         to Category.CAT_FOOD,
        "com.lidl.android"                           to Category.CAT_FOOD,
        "com.tesco.android"                          to Category.CAT_FOOD,
        "com.kroger.android"                         to Category.CAT_FOOD,
        "com.walgreens.android"                      to Category.CAT_FOOD,
        "com.cookpad.android"                        to Category.CAT_FOOD,
        "com.bigoven.android"                        to Category.CAT_FOOD,
        "com.sidechef.android"                       to Category.CAT_FOOD,
        "com.mealime.android"                        to Category.CAT_FOOD,
        "com.sok.android"                            to Category.CAT_FOOD,
        "com.gratis.android"                         to Category.CAT_FOOD,
        "com.rossmann.android"                       to Category.CAT_FOOD,
        "com.watsons.android"                        to Category.CAT_FOOD,

        // -- NEWS -- ek ---------------------------------------------------------
        "com.ap.android"                             to Category.CAT_NEWS,
        "com.usatoday.android"                       to Category.CAT_NEWS,
        "com.foxnews.android"                        to Category.CAT_NEWS,
        "com.abcnews.android"                        to Category.CAT_NEWS,
        "com.nbcnews.android"                        to Category.CAT_NEWS,
        "com.cbsnews.android"                        to Category.CAT_NEWS,
        "com.huffpost.android"                       to Category.CAT_NEWS,
        "com.economist.android"                      to Category.CAT_NEWS,
        "com.marketwatch.android"                    to Category.CAT_NEWS,
        "com.inoreader.android"                      to Category.CAT_NEWS,
        "com.mozilla.pocket"                         to Category.CAT_NEWS,
        "com.instapaper.android"                     to Category.CAT_NEWS,
        "com.getpocket.android"                      to Category.CAT_NEWS,
        "com.bianet.android"                         to Category.CAT_NEWS,
        "com.dha.android"                            to Category.CAT_NEWS,
        "com.anadoluajansi.android"                  to Category.CAT_NEWS,
    )

    fun classifyApp(appInfo: AppInfo): String {
        exactMatchMap[appInfo.packageName]?.let { return it }
        if (manufacturerClassifyEnabled) {
            classifyByManufacturerPrefix(appInfo.packageName)?.let { return it }
        }
        return classifyByKeywords(appInfo.appName, appInfo.packageName) ?: Category.CAT_OTHER
    }

    fun classifyApps(apps: List<AppInfo>): Map<String, String> =
        apps.associateBy({ it.packageName }, { classifyApp(it) })

    fun getConfidence(appInfo: AppInfo, categoryId: String): Int = when {
        categoryId == Category.CAT_OTHER -> 30
        hasExactMatch(appInfo.packageName, categoryId) -> 95
        hasKeywordMatch(appInfo.appName, categoryId) -> 80
        hasPackageKeywordMatch(appInfo.packageName, categoryId) -> 70
        else -> 50
    }

    // Üretici paket prefix'i → kategori eşleşmesi (exactMap'ten sonra, keyword'den önce)
    private fun classifyByManufacturerPrefix(packageName: String): String? {
        val pkg = packageName.lowercase()
        return MANUFACTURER_PREFIX_MAP.entries.firstOrNull { (prefix, _) -> pkg.startsWith(prefix) }?.value
    }

    private fun classifyByKeywords(appName: String, packageName: String): String? {
        val lowerName = appName.lowercase()
        val lowerPkg  = packageName.lowercase()
        KeywordDatabase.getKeywordMap().forEach { (category, keywords) ->
            keywords.forEach { kw ->
                if (lowerName.contains(kw) || lowerPkg.contains(kw)) return category
            }
        }
        return null
    }

    private fun hasExactMatch(packageName: String, categoryId: String) =
        exactMatchMap[packageName] == categoryId

    private fun hasKeywordMatch(appName: String, categoryId: String) =
        KeywordDatabase.getKeywords(categoryId).any { appName.lowercase().contains(it) }

    private fun hasPackageKeywordMatch(packageName: String, categoryId: String) =
        KeywordDatabase.getKeywords(categoryId).any { packageName.lowercase().contains(it) }
}
